language: php
sudo: required
dist: trusty

env:
  global:
  - REPO=orangehrm/orangehrm-environment-images
  - TAG=prod-7.2

#matrix:
#    include:
#        - os: linux
#          dist: trusty

  matrix:
  - TEST=unit
  - TEST=functional
  - TEST=acceptance

services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update
  - docker build -t $REPO:$TAG docker-image

install:
  - docker-compose up -d
  - composer install
  - docker ps

script:
  - php vendor/bin/codecept run $TEST

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO:$TAG


