language: php
sudo: required

env:
  global:
  - REPO=orangehrm/orangehrm-environment-images
  - TAG=prod-5.6
  matrix:
  - TEST_SUITE=unit
  - TEST_SUITE=functional
  - TEST_SUITE=acceptance


dist: trusty

services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update
  - docker build -t $REPO:$TAG docker-image

install:
  - docker-compose up -d
  - composer install
  - docker ps

stage: test
script:
  - php vendor/bin/codecept run $TEST_SUITE


jobs:
  include:
    - stage: deploy
      env:
      install: skip
      after_success:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push $REPO:$TAG