language: php
sudo: required
dist: trusty

env:
  global:
    - REPO=orangehrm/orangehrm-environment-images
    - TAG=prod-7.1-ubuntu-18.04

services:
  - docker

cache:
    directories:
      - vendor
      - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update

install:
  - docker-compose up -d
  - composer install
  - docker ps

script:
  - php vendor/bin/codecept run unit