language: php
sudo: required
dist: trusty

env:
  matrix:
    - TEST_STAGE=unit
    - TEST_STAGE=functional

services:
  - docker

cache:
    directories:
      - vendor
      - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update

install:
  - docker-compose up -d
  - composer install
  - docker ps
  - docker exec prod_phpmyadmin apt update && apt install -y iputils-ping

script:
  - php vendor/bin/codecept run $TEST_STAGE