language: php
sudo: required

php: 5.4

env:
  global:
  - REPO=orangehrm/orangehrm-environment-images
  - TAG=prod-5.4-debian

matrix:
    include:
        - os: linux
          dist: trusty          
services:
  - docker

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - uname -a
  - php --version
  - docker version
  - composer self-update
  - docker build -t $REPO:$TAG docker-image

install:
  - docker-compose up -d
#  - composer install
  - docker ps

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO:$TAG


