version: '2'
services:
  web:
    image: orangehrm/orangehrm-environment-images:prod-7.2
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/apache2/sites-available:/etc/apache2/sites-available
      - ./config/apache2/cert:/etc/apache2/cert
      - /etc/localtime:/etc/localtime
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    restart: always
    hostname: orangehrm-prod-web
    container_name: prod_web


