on:
  push:
    branches: [ php-7.4-ubuntu-20.04 ]
    
env:
  REPO: "orangehrm/orangehrm-environment-images"
  TAG: "prod-php-7.4-ubuntu20.04" 
  DOCKER_HUB_REPO: "us95123"
  LATEST_TAG: "ubuntu20"
  
jobs:

    build:

      runs-on: ubuntu-latest
      steps: 
       
       - name: Get the checkout  
         uses: actions/checkout@v3

       - name: Prerequisites
         run: |
           uname -a
           php --version
           docker --version
           docker-compose --version
           composer --version

       - name: Install test suite dependencies
         run: |
           composer update
           composer install
           docker ps        
        
       - name: Build docker image
         run: docker build -t ${{ env.REPO }}:${{ env.TAG }} docker-image  

       - name: Up the container
         run: |
           docker-compose up -d
           docker ps

       - name: Unit test 
         run: php vendor/bin/codecept run unit

       - name: Login to docker hub
         uses: docker/login-action@v2
         with: 
           username: ${{secrets.DOCKER_HUB_UN}} 
           password: ${{secrets.DOCKER_HUB_PW}}

       - name: tag the docker image 
         run: docker tag ${{ env.REPO }}:${{ env.TAG }} ${{env.DOCKER_HUB_REPO}}/${{ env.REPO }}:${{ env.LATEST_TAG }}

       - name: push the image 
         run: docker push ${{env.DOCKER_HUB_REPO}}/${{ env.REPO }}:${{ env.LATEST_TAG }}
        
       
      